### ISSUE TITLE
Crosspost wird nicht im Life Feed angezeigt

### ISSUE THREAD

**Issue by SHaagmann** [KingMarcel/social_issues#27]
**Beobachtetes Verhalten**
Wenn man ein Bild auf das Profil eines anderen Postet wird dieses nicht im Life Feed angezeigt, auch wenn beide Personen es aktiv haben, dass es dort angezeigt werden müsste

**Erwartetes Verhalten**
Wird im Life Feed angezeigt, wenn dies nicht deaktiviert wurde

**Schritte um den Fehler nachvollziehen zu können**
Bild auf das Profil einer anderen Person Posten

**Comment by KMDEV-Marcel** [comment]
fixed
